---
output:
  html_document: 
    toc: true
    toc_float: true
---

# Course


|   Focus on |      Course      |  Made by |
|----------------|:---------------------------------:|-----------------:|
|Data Science |[Intro to Data Science](https://www2.stat.duke.edu/courses/Spring18/Sta199/) | RStudio|
|Data Science| [Supervised Machine Learning  Case Studies in R](https://supervised-ml-course.netlify.app/)|Julia Silge |
|Data Science|[Data Science course in a box](https://github.com/rstudio-education/datascience-box)|RStudio|
|Data Science|[Data Science for Social Science](http://datascience.tntlab.org/schedule-materials/)|RICHARD N. LANDERS|
|R|[Introduction to R](https://ramnathv.github.io/pycon2014-r/)|idocs|
|R|[Introduction to R](http://uc-r.github.io/introduction)|UC|
|R | [Intro to R](https://www.youtube.com/playlist?list=PLOU2XLYxmsIK9qQfztXeybpHvru-TrqAP)|google|
|Biomedical|[Biomedical Data Science](http://genomicsclass.github.io/book/)|R. Irizarry and M. Love|
|Shiny|[Learn Shiny](https://shiny.rstudio.com/tutorial/)|RStudio|
|Data Science|[Data science in R](http://courses.had.co.nz/12-oscon/)|Hadley Wickham|
|Programming|[R development master class](http://courses.had.co.nz/12-devtools/)|Hadley Wickham|
|Data Science|[Big data summer institute](http://courses.had.co.nz/12-rice-bdsi/)|Hadley Wickham|
|Programming|[Package development](http://courses.had.co.nz/11-csiro/)|Hadley Wickham|
|Visualisation|[Data visualisation in R with ggplot2 and plyr](http://courses.had.co.nz/11-rice/)|Hadley Wickham| 
|Data Science|[Introduction to data analysis](http://had.co.nz/stat405/)|Hadley Wickham|
|R|[Introduction to R & RStudio](https://github.com/AmeliaMN/IntroToR)|McNamara|
|Data Analysis|[Data Analysis and Visualization Using R](http://varianceexplained.org/RData/)|David Robinson|
|R|[Data wrangling, exploration, and analysis with R](http://stat545.com/)|UBC|
|Data Science|[Statistics and R](http://rafalab.github.io/pages/harvardx.html)|Harvard|
|Bioconductor|[Bioconductor for Genomic Data Science](https://kasperdanielhansen.github.io/genbioconductor/)|K. D. Hansen|
|Data Analysis <kbd>*</kbd>|[R for data analysis and visualization of Ecological Data](https://datacarpentry.org/R-ecology-lesson/index.html#chapters)|Data Carpentry|
|Data Analysis<kbd>*</kbd>|[Data Analysis and Visualization in R](https://datacarpentry.org/R-genomics/index.html)|Data Carpentry|
|Data Science|[Earth Data Science Tutorials in R](https://www.earthdatascience.org/tutorials/r/)|University of Colorado|
|Data Science|[An Introduction to Statistical Learning](https://www.dataschool.io/15-hours-of-expert-machine-learning-videos/)|Stanford University|
|Social Science|[2018 Summer Institute in Computational Social Science](https://compsocialscience.github.io/summer-institute/2018/teaching-learning-materials)|Duke University|
|Data Science|[Data Science in a Box](https://datasciencebox.org/)|RStudio|
|Journalism|[R for journalists](https://learn.r-journalism.com/en/)|Andrew Ba Tran|
|Visualization|[From Data to Insight](http://www2.stat.duke.edu/~mc301/ARTSCI101_Su16/)|MINE ÇETINKAYA-RUNDEL|
|Programming|[Programming with R](https://swcarpentry.github.io/r-novice-inflammation/)|Carpentries|
|Visualization|[R graphics with ggplot2 workshop notes](https://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html#geometric_objects_and_aesthetics)|Harvard University|
|Visualization|[Introduction to Data Visualization](http://paldhous.github.io/ucb/2016/dataviz/index.html)|Peter Aldhous|
|Visualization|(Information Visualization)[http://enrico.bertini.io/teaching/]|Enrico Bertini|
|Data Analysis|[Business Analytics in R](http://lab.rady.ucsd.edu/sawtooth/business_analytics_in_r/index.html)|Karsten T. Hansen|
|Bioconductor|[RNA-Seq Analysis with R and Bioconductor](http://girke.bioinformatics.ucr.edu/CSHL_RNAseq/)|UC Riverside|
|Data Analysis|[The Research Cycle](https://rgup.gitlab.io/research_cycle/index.html)| D. Barr and L. DeBruine|
|Data Analysis|[R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/)|Carpentries|
Data Analysis|[Analyzing large-scale biomedical data with R](https://bims.fun/index.html)|Virginia University|
|R|[INTRODUCTION TO R](http://usepa.github.io/introR/)|Jeff Hollister|
|Data Analysis|[Reproducible Science](https://gupsych.github.io/data_skills/index.html)|D. Barr and L. DeBruine|
|Programming|[Introduction to R Programming <kbd>*</kbd>](https://github.com/jameslamb/teaching/tree/master/mu_rprog)|Marquette University|
|Data Analysis|[Data management and manipulation using R](https://ozanj.github.io/rclass/)|University of California|
|Data Science|[Data science for economists](https://github.com/uo-ec607/lectures)|Grant McDermott|
|DOE|[From Data to Decisions](http://www.lithoguru.com/scientist/statistics/course.html)|Chris Mack|
|R|[Intro to R](https://github.com/uc-r/Intro-R)|University of Cincinnati|
|R|[Intermediate R](https://github.com/uc-r/Intermediate-R)|University of Cincinnati|
|Data Analysis|[Advanced Analytics with R](https://github.com/uc-r/Advanced-R)|University of Cincinnati|
|Shiny| [Shiny Workshop](https://github.com/sshawna/Shiny_workshop)|Marine Istitute|
|Spatial Analysis | [Mapping with R](https://github.com/andrewbtran/NICAR-2019-mapping) |Andrew Tran |
|Digital Analytics| [Digital Analytics: R and staTISTICS](http://www.dartistics.com/index.html) |M. Edmondson & T. Wilson|
|Spatial Analysis| [Spatial Data Science with R](https://www.rspatial.org/index.html)|Robert J. Hijmans|
|Programming|[Advanced R Course](https://privefl.github.io/advr38book/)|F. Privé|
|Econometrics|[Data science for economists](https://github.com/uo-ec607/lectures)|G. McDermott|
|Econometrics|[Econometrics](https://github.com/edrubin/EC525S19)| E. Rubin|
|Visualization|[Data analytics and visualization](https://www.yan-holtz.com/teaching)|Yan Holtz|
|Visualization| [Data Visualization in R](http://www.datavis.ca/courses/RGraphics/)|Michael Friendly|
|Spatial Analysis| [Data wrangling visualisation and spatial analysis](http://www.seascapemodels.org/data/data-wrangling-spatial-course.html#41_data_wrangling_and_plotting_with_tidyverse) |Seascape models | 
|Genomics |[Plotting in R for Biologists](http://marianattestad.com/blog)|Maria Nattestad|
|Data Analysis|[Data Skills for Reproducible Science](https://gupsych.github.io/data_skills/)|Dale Barr and Lisa DeBruine|
|Data Science|[Data Science with R](https://p8105.com/schedule.html)|Jeff Goldsmith|
|Time Series| [Time Series Boot Camp](https://github.com/jlukito/timeseries-bootcamp)|J. Lukito and J. Foley|
|Time Series|[
Applied Time Series Analysis](https://newonlinecourses.science.psu.edu/stat510/)|The Pennsylvania State University|
|Data Analysis|[Exploratory Data Analysis in R](https://mgimond.github.io/ES218/index.html)|Manny Gimond|
|Data Science|[Tidy Data Science](https://tidy-ds.wjakethompson.com/)|Jake Thompson|
|Shiny|[Shiny Workshop](https://osf.io/69j37/files/)|Sonja Winter & Katie Coburn|
|Data Science|[Master Tidyverse](https://github.com/rstudio/master-the-tidyverse)|Garrett Grolemund|
|Data Science|[R bootcamp](https://r-bootcamp.netlify.com/)|T. Laderas & J. Minnier|
|R Docker|[A Docker tutorial for reproducible research](http://ropenscilabs.github.io/r-docker-tutorial/)|ropenscilabs|
|Data Analysis|[QCBS R Workshops](https://wiki.qcbs.ca/r)|QCBS|
|Data Science| [Introduction to Data Science](https://datasciencelabs.github.io/)|Harvard|
|Shiny|[Shiny Tutorials](https://psyteachr.github.io/shiny-tutorials/)|Teaching Reproducible Psychology|
|Data Analysis|[Analytics for industRy](https://garthtarr.github.io/meatR/index.html)|Garth Tarr|
|Data Analysis|[R for Reproducible Research](https://annakrystalli.me/rrresearch/index.html)|Anna Krystalli|
|Data Science|[Applied Machine Learning short course at R/Pharma 2019](https://github.com/tidymodels/aml-training/tree/master/half%20day)|Max Kuhn |
|Data Science|[Data Science Essentials in R
Introduction](https://uvastatlab.github.io/phdplus/index.html)|PhDPlus |
|Tidyverse|[R Bootcamp interactive course](https://r-bootcamp.netlify.com/)|T. Laderas & J. Minnier|
|Market Analysis|[Market Analysis with Econometrics and Machine Learning](https://github.com/skranz/MarketAnalysis)|Sebastian Kranz|








Other website like this:

* [rstats-ed](https://github.com/rstudio-education/rstats-ed)
