---
output:
  html_document: 
    toc: true
    toc_float: true
---


# Ebook 

* [Introduction to Open Data Science](https://ohi-science.org/data-science-training/)

* [R for Data Science](https://r4ds.had.co.nz/)

* [Introduction to Programming with R](https://eeecon.uibk.ac.at/~discdown/rprogramming/introduction.html)

* [Twitter for R programmers](https://www.t4rstats.com/)

* [R Packages](https://r-pkgs.org/)

* [Happy Git and GitHub for the useR](http://happygitwithr.com/)

* [Just Enough R](https://benwhalley.github.io/just-enough-r/)

* [An Introduction to Statistical and Data Sciences via R](http://moderndive.com/index.html)

* [Feature Engineering and Selection: A Practical Approach for Predictive Models](http://www.feat.engineering/)

* [Data Science in Education Using R](https://datascienceineducation.com/)

* [Functional programming and unit testing for data munging with R](https://b-rodrigues.github.io/fput/)

* [Passion Driven Statistics](https://alanarnholt.github.io/PDS-Bookdown2/)

* [Introduction to Data Science](https://rafalab.github.io/dsbook/)

* [plotly for R](https://plotly-book.cpsievert.me/index.html)

* [Tidyverse Skills for Data Science](https://jhudatascience.org/tidyversecourse/)

* [Foundations of Data Science](http://www.cs.cornell.edu/jeh/book.pdf)

* [Materials to accompany the book Learning from Data: An Introductory Handbook Using R](https://github.com/kjmazidi/Learning_from_Data)

* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)

* [Flexible Imputation of Missing Data](https://stefvanbuuren.name/fimd/)

* [Fundamentals of Data Visualization](http://serialmentor.com/dataviz/)

* [Forecasting: Principles and Practice](https://otexts.org/fpp2/)

* [Data Visualization](http://socviz.co/)

* [Learning statistics in R](https://ademos.people.uic.edu/index.html)

* [Getting used to R, RStudio, and R Markdown](https://rbasics.netlify.com/index.html)

* [Intro to GIS and Spatial Analysis](https://mgimond.github.io/Spatial/index.html)

* [Spatial Data Analysis and Modeling with R](http://www.rspatial.org/index.html)

* [h2o tutorials](http://docs.h2o.ai/h2o-tutorials/latest-stable/)

* [Geocomputation with R](https://geocompr.robinlovelace.net/)

* [Hands-on Machine Learning with R](https://bradleyboehmke.github.io/hands-on-machine-learning-with-r/)

* [A gRadual intRoduction to Shiny](https://laderast.github.io/gradual_shiny/)

* [Technical Foundations of Informatics](https://info201.github.io/)

* [Hands-On Programming with R](https://rstudio-education.github.io/hopr/)

* [The tidyverse style guide](http://style.tidyverse.org/)

* [R Models - Quick reference](https://m-clark.github.io/R-models/#introduction)

* [Analytics with R](http://analyticswithr.com/index.html)

* [AVML 2012: ggplot2](https://www.ling.upenn.edu/~joseff/avml2012/)

* [R for Statistical Learning](https://daviddalpiaz.github.io/r4sl/)

* [ComplexHeatmap Complete Reference](https://jokergoo.github.io/ComplexHeatmap-reference/book/)

* [ggplot2 graphics companion](https://www.trafforddatalab.io/graphics_companion/#ggplot2_graphics_companion)

* [Statistical Thinking for the 21st Century](http://thinkstats.org/)

* [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/)

* [Creating APIs in R with Plumber](https://www.rplumber.io/docs/index.html)

* [Learning statistics with R](https://learningstatisticswithr-bookdown.netlify.com/) [website](https://learningstatisticswithr.com/)

* [Data Analysis in Ecology with R and Stan](https://tobiasroth.github.io/BDAEcology/index.html)

* [The Hundred-Page Machine Learning Book](http://themlbook.com/wiki/doku.php)

* [Tidy Evaluation](https://tidyeval.tidyverse.org/)

* [Introduction to Econometrics with R](https://www.econometrics-with-r.org/index.html)

* [Regression Models for Data Science in R](https://leanpub.com/regmods/read#leanpub-auto-residuals)

* [Pack YouR Code](https://github.com/gastonstat/plsdepot)

* [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/)

* [The R Manuals](https://cran.r-project.org/manuals.html)

* [Spatial Data Science](https://keen-swartz-3146c4.netlify.com/)

* [A Survival Guide to Data Science with R ](https://togaware.com/onepager/)

* [Introduction to R](https://intro-r.rsquaredacademy.com/)

* [Data Wrangling with R](https://wrangle-r.rsquaredacademy.com/)

* [Data Visualization with ggplot2](https://viz-ggplot2.rsquaredacademy.com/)

* [Data Visualization with R](https://viz-base.rsquaredacademy.com/)

* [R, Databases & SQL](https://rdbsql.rsquaredacademy.com/)

* [Building Big Shiny Apps - A Workflow](https://thinkr-open.github.io/building-shiny-apps-workflow/)

* [Data Wrangling with R](https://cengel.github.io/R-data-wrangling/)


* [R Graphics Cookbook](https://r-graphics.org/)

* [Feature Engineering and Selection: A Practical Approach for Predictive Models](https://bookdown.org/max/FES/)


* [Predictive Models: Visual Exploration, Explanation and Debugging](https://pbiecek.github.io/PM_VEE/)

* [Data Visualization with R](https://cengel.github.io/R-data-viz/)

* [Introduction to Open Data Science](http://ohi-science.org/data-science-training/)

* [R, Databases, and Docker](https://smithjd.github.io/sql-pet/)

* [Learning Statistics in R](https://ademos.people.uic.edu/index.html)

* [Hands-on Machine Learning with R](https://bradleyboehmke.github.io/HOML/index.html#why-r)

* [R Advanced Spatial Lessons](http://benbestphd.com/R-adv-spatial-lessons/)

* [An Introduction to Machine Learning with R](https://lgatto.github.io/IntroMachineLearningWithR/index.html)

* [RMarkdown for Scientists](https://rmd4sci.njtierney.com/)

* [Data Science Practice](https://datasciencepractice.study/)

* [Agile Machine Learning with R](https://bookdown.org/edwinthoen/AMLwR/)

* [Data Science with R: A Resource Compendium](https://bookdown.org/martin_monkman/DataScienceResources_book/)

* [The wikipedia of R by me](https://r-pedia.gitbook.io/cevi/)

* [MSc Conversion in Psychological Studies/Science](https://psyteachr.github.io/msc-conv-f2f/)

* [Data Skills for Reproducible Science](https://psyteachr.github.io/msc-data-skills/)

* [Intro Regression](https://www.introregression.org/)

* [Applied missing data analysis](https://bookdown.org/mwheymans/Book_MI/)

## Programming

* [Writing R extensions](https://colinfay.me/writing-r-extensions/index.html)

* [Efficient R programming](https://csgillespie.github.io/efficientR/)

* [Computational Genomics with R](https://compgenomr.github.io/book/)

## Shiny

* [Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/index.html)

* [Mastering Shiny](https://mastering-shiny.org/)

* [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/)

* [Shiny Production with AWS Book](https://business-science.github.io/shiny-production-with-aws-book/)

* [Outstanding User Interfaces with Shiny](https://divadnojnarg.github.io/outstanding-shiny-ui/?s=09)
----

# Ebook Collection

* [20 Free Online Books to Learn R and Data Science](https://cmdlinetips.com/2018/01/free-online-resources-books-to-learn-r-and-data-science/)

* [Books for learning R](https://github.com/jl5000/r_ebooks)

* [Useful books by Suzan Baert](https://github.com/suzanbaert/Resources_and_Bookmarks/blob/master/1_R_Books.md)

* [Books related to R](https://www.r-project.org/doc/bib/R-books.html)


* [Top R language resources to improve your data skills](https://www.computerworld.com/article/2497464/business-intelligence/top-r-language-resources-to-improve-your-data-skills.html?nsdr=true&page=2)

* [A curated list of awesome R packages, frameworks and software](https://awesome-r.com/)


* [100 Free R Tutorials and Resources in University webpages](https://pairach.com/2012/02/26/r-tutorials-from-universities-around-the-world/)


* [Top 6 Free E-Books To Learn R At Beginner And Advanced Levels](https://analyticsindiamag.com/top-6-free-e-books-to-learn-r-at-beginner-and-advanced-levels/)

* [What are some good resources for learning R?](https://www.quora.com/What-are-some-good-resources-for-learning-R-1)

* [FREE R READING MATERIAL](https://committedtotape.shinyapps.io/freeR/)

* [Data Science Learning Resources](https://github.com/bradleyboehmke/data-science-learning-resources)

----


# R book in italian

* [Statistica per Data Science con R](http://www.r-project.it/_book/index.html)