---
output:
  html_document: 
    toc: true
    toc_float: true
---



# Get the data


> readr

the goal of `readr` is to provide a fast and friendly way to read rectangular data. 
[readr - vignettes](https://cran.r-project.org/web/packages/readr/vignettes/readr.html)

> rio

The idea behind rio is to simplify the process of importing data into R and exporting data from R. 
[rio - vignettes](https://cran.r-project.org/web/packages/rio/vignettes/rio.html)

> dplyr

`dplyr` is a grammar of data manipulation, providing a consistent set of verbs that help you solve the most common data manipulation challenges
[dplyr - website](https://dplyr.tidyverse.org/)
[dplyr - vignettes](https://cran.r-project.org/web/packages/dbplyr/vignettes/dbplyr.html)

> MonetDBLite

MonetDBLite for R, a fully embedded version of MonetDB that installs like any other R package.

> bigreadr

Convert a CSV to SQLite by parts

[bigreadr - website](https://privefl.github.io/bigreadr/index.html)

# Data Trasformation

> forcats

The goal of the forcats package is to provide a suite of useful tools that solve common problems with factors.

[forcats - website](http://forcats.tidyverse.org/)

# Simulating dataset

> Xy

Simulating Supervised Learning Data
[Xy -- github](https://github.com/andrebleier/Xy)

> synthpop

A tool for producing synthetic versions of microdata containing confidential information
[synthpop -- blogpost](http://gradientdescending.com/generating-synthetic-data-sets-with-synthpop-in-r/3456yuhjtnbf vc)

> holodeck 

A Tidy Interface For Simulating Multivariate Data
[holodeck -- github](https://github.com/Aariq/holodeck)

> fakir

Create Fake Data in R for tutorials
[fakir -- github](https://github.com/ThinkR-open/fakir)

# Explorative data analysis

> skimr

display summary statistics that the user can skim quickly to understand their data.

[skimr - githun](https://github.com/ropensci/skimr)

> SmartEDA

Summarize and Explore the Data 

[SmartEDA - vignettes](https://cran.r-project.org/web/packages/SmartEDA/vignettes/Report_r1.html)

> FunModeling

`funModeling`: data cleaning, importance variable analysis and model perfomance

[funModeling - github](https://github.com/pablo14/funModeling)

> DataExplorer

Data exploration process for data analysis and model building, so that users could focus on understanding data and extracting insights. The package automatically scans through each variable and does data profiling. 

[DataExplorer - vignettes](https://cran.r-project.org/web/packages/DataExplorer/vignettes/dataexplorer-intro.html)
[DataExplorer - github](https://boxuancui.github.io/DataExplorer/index.html)


> naniar

`naniar` provides data structures and functions that facilitate the plotting of missing values and examination of imputations.

[naniar - website](http://naniar.njtierney.com/articles/naniar-visualisation.html)
[naniar - github](https://github.com/njtierney/naniar)

> dataMaid

Generating codebooks in R

* [dataMaid - vignettes](https://cran.r-project.org/web/packages/dataMaid/vignettes/extending_dataMaid.html#a-datamaid-report-with-user-defined-functions-documenting-artdata)

# Experimental Design

* `edibble`  facilitates statistical thinking of adapting experimental designs to different conditions by implementing the grammar of experimental design to generate new designs

[edibble - github](https://github.com/emitanaka/edibble)


# Dimension Reduction (PCA)

> FactoMineR

`FactoMineR` is an R package dedicated to multivariate Exploratory Data Analysis.

[FactoMineR - website](http://factominer.free.fr/)

> umap

R implementation of Uniform Manifold Approximation and Projection

[umap - github](https://github.com/tkonopka/umap)

# Clustering

> fpc

Various methods for clustering and cluster validation.


> gower

Gower’s distance can be used to measure how different two records are.

[gower - vignettes](https://cran.r-project.org/web/packages/gower/vignettes/intro.html)

> ggbiplot

An implementation of the biplot using `ggplot2`. The package provides two functions: `ggscreeplot()` and `ggbiplot()`. 

[ggbiplot - github](https://github.com/vqv/ggbiplot)

> dimRed

A collection of dimensionality reduction techniques from R packages and a common interface for calling the methods.

[dimRed - CRAN](https://cran.r-project.org/web/packages/dimRed/index.html)


# Visualization

> ggplot2

`ggplot2` is a system for declaratively creating graphics, based on The Grammar of Graphics.

[ggplot2 - website](http://ggplot2.tidyverse.org/)

> GGally

`GGally` extends ggplot2 by adding several functions to reduce the complexity of combining geoms with transformed data.

[GGally - website](https://ggobi.github.io/ggally/)

> ggpubr

The `ggpubr` package provides some easy-to-use functions for creating and customizing ‘ggplot2’- based publication ready plots.

[ggpubr - sthda website](http://www.sthda.com/english/rpkgs/ggpubr/index.html)

> ggrepel

Repel overlapping text labels away from each other

[ggrepel - vignettes](https://github.com/slowkow/ggrepel)

> ggrough

’ggrough’ is an R package that converts your ggplot2 plots to rough/sketchy charts, using the excellent javascript roughjs library

[ggrough -- website](https://xvrdm.github.io/ggrough/)

> tabplot

The tableplot is a powerful visualization method to explore and analyse large multivariate datasets

[tabplot - vignettes](https://cran.r-project.org/web/packages/tabplot/vignettes/tabplot-vignette.html)

> ggstatsplot

creates graphics with details from statistical tests
[ggstatsplot - github](https://github.com/IndrajeetPatil/ggstatsplot)

> plotly

An R package for creating interactive web graphics.

[plotly - github](https://github.com/ropensci/plotly)

> patchwork

The goal of `patchwork` is to make it ridiculously simple to combine separate ggplots into the same graphic. 
[patchwork - github](https://github.com/thomasp85/patchwork/blob/master/README.md) 

> factoextra

`factoextra` is an R package making easy to extract and visualize the output of exploratory multivariate data analyses

[factoextra - sthda website](http://www.sthda.com/english/wiki/factoextra-r-package-easy-multivariate-data-analyses-and-elegant-visualization)

> ggiraphExtra

`ggiraphExtra` contains many useful functions for exploratoty plots.

[ggiraphExtra - vignettes](http://rpubs.com/cardiomoon/231820)

> r2d3

R Interface to D3 Visualizations

[r2d3 -- webiste](https://rstudio.github.io/r2d3/index.html)

> xda

R package for exploratory data analysis 

[xda - github](https://github.com/ujjwalkarn/xda)

> gghighlight

Highlight points and lines in ggplot2

[gghighlight -- github](https://github.com/yutannihilation/gghighlight)

> bbplot

It helps create and export ggplot2 charts in the style used by the BBC News data team

[bbplot -- site](https://bbc.github.io/rcookbook/)

# Machine Learning

> SuperML

[SuperML - website](https://saraswatmks.github.io/superml/index.html)

> caret

The `caret` package (short for Classification And REgression Training) contains functions to streamline the model training process for complex regression and classification problems.
[caret - vignettes](https://cran.r-project.org/web/packages/caret/vignettes/caret.html)

> mlr

`mlr` is a framework for machine learning experiments in R.
[mlr - website](https://mlr-org.github.io/mlr-tutorial/release/html/index.html)
[mlr - blog](https://mlr-org.github.io/)

> Metrics

An R package for common supervised machine learning metrics 
[Metrics - github](https://github.com/mfrasco/Metrics)


> iml

The `iml` package provides tools for analysing any black box machine learning model.
[iml - vignettes](https://cran.r-project.org/web/packages/iml/vignettes/intro.html)

> lime

The purpose of `lime` is to explain the predictions of black box classifiers
[lime - vignettes](https://cran.r-project.org/web/packages/lime/vignettes/Understanding_lime.html)
[lime - github](https://github.com/thomasp85/lime)

> xgboostExplaine

An R package that makes xgboost models fully interpretable
[xgboostExplainer - tutorial](https://medium.com/applied-data-science/new-r-package-the-xgboost-explainer-51dd7d1aa211) 

> shapper

The SHAP method is used to calculate influences of variables on the particular observation. 

[shapper - blogpost](http://smarterpoland.pl/index.php/2019/03/shapper-is-on-cran-its-an-r-wrapper-over-shap-explainer-for-black-box-models/)

> shinyMlr

Integration of the mlr package into shiny.
With help of this package mlr can be accessed via a shiny interface.

[shinyMlr - github](https://github.com/mlr-org/shinyMlr)
[shinyMlr - video tutorial](https://www.youtube.com/watch?v=VZuRSQZdayY&list=PLcTJ-34ghaH2QGL73DWfQvIdacW01Nvtp)

> bounceR

`bounceR` provides methods and tools for automated feature selection for Machine Learning models. The methods are fit for situation in which the data scientists faces an exceedingly high number of features.

[bounceR - github](https://github.com/STATWORX/bounceR) )

> recipes

`recipes` is an alternative method for creating and preprocessing design matrices that can be used for modeling or visualization.
[recipes - github](https://github.com/topepo/recipes)

> modelDown

`modelDown` generates a website with HTML summaries for predictive models 
[modelDown - vignettes](modelDown generates a website with HTML summaries for predictive models)

> dalex

`DALEX` is a set of tools that help to understand how complex models are working.
[dalex -- website](https://pbiecek.github.io/DALEX/)

> iBreakDown

Model Agnostic Explainers for Individual Predictions
The `iBreakDown` package is a model agnostic tool for explanation of predictions from black boxes ML models.
[iBreakDown -- website](https://modeloriented.github.io/iBreakDown/)

> rpart.plot

It extends the functions in the rpart package
[rpart.plot -- website](http://www.milbo.org/rpart-plot/index.html)

# Association rules

> arules

Mining Association Rules and Frequent Itemsets with R
[arules - github](https://github.com/mhahsler/arules)

# Time series

> tsfknn

The package allows, with only a function, to specify the KNN model and to generate the forecasts. 
[tsfknn - vignettes](https://cran.r-project.org/web/packages/tsfknn/vignettes/tsfknn.html)

> prophet

Prophet is a procedure for forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects.
[prohet - website](https://facebook.github.io/prophet/) 

> breakDown

Model Agnostic Explainers for Individual Predictions

[breakdown - website](https://pbiecek.github.io/breakDown/index.html)


> ggTimeSeries

This R package offers novel time series visualisations. It is based on ggplot2 and offers geoms and pre-packaged functions for easily creating any of the offered charts. Some examples are listed below.
[ggTimeSeries - vignettes](https://cran.r-project.org/web/packages/ggTimeSeries/vignettes/ggTimeSeries.html)

> tsbox

tsbox: Class-Agnostic Time Series in R

[tsbox - website](https://www.tsbox.help/index.html)

> tsutils

The tsutils package for R provides functions to support various aspects of time series and forecasting modelling.

[tsutils - github](https://github.com/trnnick/tsutils)

# R Interface

> sparkryl

`sparklyr` is an R interface for Apache Spark

[sparklyr - website](http://spark.rstudio.com/)


> RWeka

An R interface to Weka. Weka is a collection of machine learning algorithms for data mining tasks written in Java.

> rbokeh

rbokeh is an R Interface for Bokeh. Bokeh is a visualization library that provides a flexible and powerful declarative framework for creating web-based plots
[rbokeh - vignettes ](http://hafen.github.io/rbokeh/#background)

# Spatial Analysis

> cartography

This package allows various cartographic representations such as proportional symbols, choropleth, typology, flows or discontinuities maps.
[cartography -- github](https://github.com/riatelab/cartography)


# Deep Learning interface

> h2o

R scripting functionality for 'H2O', the open source math engine for big data that computes parallel distributed machine learning algorithms such as generalized linear models, gradient boosting machines, random forests, and neural networks (deep learning) within various cluster environments.

[h2o - website](http://docs.h2o.ai/h2o/latest-stable/h2o-r/docs/index.html)


[h2o - tutorial](https://github.com/h2oai/h2o-tutorials/tree/master/tutorials/deeplearning)


> Keras

R interface to Keras
[keras - website](https://tensorflow.rstudio.com/keras/)


# Big-Data

> ff

The ff package provides data structures that are stored on disk but behave (almost) as if they were in RAM.
[ff - website](http://ff.r-forge.r-project.org/)

> replyr

The `replyr` package attempts to provide practical data manipulation affordances to make code perform similarly on local or remote (big) data.
[replyr - github](https://github.com/WinVector/replyr)

> disk.frame


Fast disk-based parallelized data manipulation framework for larger-than-RAM data

[disk.frame - github](https://github.com/xiaodaigh/disk.frame)

# Deploy

> aurelius

Provides tools for converting R objects and syntax into the Portable Format for Analytics (PFA). 
[aurelius - vignettes](https://cran.r-project.org/web/packages/aurelius/vignettes/basic-usage.html)

> plumber

It converts your existing R code to a web API using a handful of special one-line comments.
[plumber -- website](https://github.com/Aariq/holodeck)

# Shiny

> shiny

`shiny` makes it easy to build interactive web apps straight from R
[shiny - website](https://shiny.rstudio.com/)

> shinydashboard

`shinydashboard` makes it easy to use Shiny to create dashboards
[shinydashboard - website](https://rstudio.github.io/shinydashboard/)

> argonDash

Argon dashboard template
[argomDash -- website](https://rinterface.github.io/argonDash/)

> shinyproxy

ShinyProxy is your favourite way to deploy Shiny apps in an enterprise context.
[shinyproxy - website](https://www.shinyproxy.io/#what-is-shinyproxy)

> shinyLP

A R package for Bootstrap Components to make Landing Home Pages for Shiny
[shinyLP - github](https://github.com/jasdumas/shinyLP)

> shinytemplate

RStudio Project Templates for Shinyapps
[shinytemplate - github](https://github.com/ThinkR-open/shinytemplate)

> shinymodule

A Shiny module is a piece of a Shiny app.
[shinymodules - shiny website](https://shiny.rstudio.com/articles/modules.html)

> dashboardthemes

custom theme support for R Shinydashboard applications
[ dashboardthemes - github](https://github.com/nik01010/dashboardthemes)

> fontawesome

The fontawesome package makes it very easy to insert FontAwesome icons within R Markdown documents and Shiny apps.
[fontawesome - github](https://github.com/rstudio/fontawesome)

> shinyWidgets 

Extend widgets available in shiny

[shinyWidgets - website](https://dreamrs.github.io/shinyWidgets/index.html)

> shinydashboardPlus

Extensions for shinydashboard
[shinydashbordpPlus -- website](https://divadnojnarg.github.io/shinydashboardPlus/index.html)


> bs4Dash

Bootstrap 4 shinydashboard using AdminLTE3
[bs4Dash -- website](https://divadnojnarg.github.io/bs4Dash/index.html)

> yonder

A Reactive Web Framework Built on Shiny
[yonder - website](https://nteetor.github.io/yonder/)

> auth0

The goal of auth0 is to implement an authentication scheme to Shiny using OAuth Apps through the freemium service Auth0.
[auth0 - website](https://curso-r.github.io/auth0/) 

> shinyEffects

Customize your shiny apps with these nice CSS effects
[shinyEffects - github](https://github.com/DivadNojnarg/shinyEffects)

> tablerDash

A new super light ✨shiny dashboard template.
[tablerDash - website](http://www.rinterface.com/shiny/tablerDash/)

> dragulaR

Drag’n’drop elements with dragulaR
[dragulaR - website](https://dragular.zstat.pl/)

> gglabeller

Shiny gadget for labeling points on ggplot
[gglabeller - github](https://github.com/AliciaSchep/gglabeller)

> ggiraph

Make ‘ggplot’ Graphics Interactive
[ggiraph -- github](http://davidgohel.github.io/ggiraph/index.html)

> excelR

An R interface to jExcel library to create web-based interactive tables and spreadsheets compatible with 'Excel' or any other spreadsheet software.
[excelR -- github](https://github.com/Swechhya/excelR)

# Reporting & Publishing results

> rmarkdorwn

Convert R Markdown documents into a variety of formats.
[rmarkdown - website](https://rmarkdown.rstudio.com/)

> icon

web icons for rmarkdown
[icon - website](https://ropensci.org/technotes/2018/05/15/icon/)

> officer

Access and manipulate 'Microsoft Word' and 'Microsoft PowerPoint' documents from R. 
[officer - vignettes](https://cran.r-project.org/web/packages/officer/vignettes/officer_reader.html)

> kableExtra

The goal of kableExtra is to help you build common complex tables and manipulate table styles.

[kableExtra - website](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html)

> slidex

slidex is aimed at making the process of converting Microsoft PowerPoint slides to beautiful HTML xaringan slides as seamless as possible, maintaining tables,figures, links, and bulleted lists.
[slidex - github](https://github.com/datalorax/slidex)

> xaringan

[xaringan - github](https://github.com/yihui/xaringan)

> gt

Make wonderful-looking tables with the gt package

[gt- github](https://rstudio.github.io/gt/)

# ODE & Quality Control

> SixSigma

Functions and utilities to perform Statistical Analyses in the Six Sigma way.

[SixSigma with R - ebook website](http://www.sixsigmawithr.com/)
[Quality Control with R - ebook](http://www.qualitycontrolwithr.com/)


> qcc

qcc is a contributed R package for statistical quality control charts
[qcc - vignettes](https://cran.r-project.org/web/packages/qcc/vignettes/qcc_a_quick_tour.html)


> ggQC

Plot single and multi-facet quality control charts within the ggplot framework using stat_QC and stat_mR. Calculate quality control limits using QC_Lines.
[ggQC - github](https://github.com/kenithgrey/ggQC)



# R API

> dockerfiler

dockerfiler is a package that comes with a simple, object oriented API for Dockerfile creation, straight from your R session.

[tutorial](http://colinfay.me/dockerfiler-cran/)

> cloudML

cloudml provides an R interface to Google Cloud Machine Learning Engine
[cloudML - website](https://tensorflow.rstudio.com/tools/cloudml/articles/getting_started.html)


> googleComputeEngineR 


provides an R interface to the Google Cloud Compute Engine API, for launching virtual machines.
[googleComputeEngineR - github](https://github.com/cloudyr/googleComputeEngineR)


# IDE

> Rcode


> R Analyticflow

# Productivity

> packagefinder

With 'packagefinder' you can search for multiple keywords in the name, title and description of the CRAN package, either case-sensitive or insensitive and define your own weighting scheme for the search results, if you like.
[ packagefinder - CRAN](https://cloud.r-project.org/web/packages/packagefinder/index.html)

> fs

fs provides a cross-platform, uniform interface to file system operations. fs uses libuv under the hood, which gives a rock solid cross-platform interface to the filesystem.
[ fs - website](https://www.tidyverse.org/articles/2018/01/fs-1.0.0/)

> pacman

A package management tools for R
[pacman - github](https://github.com/trinker/pacman)

# RStudio Addin

> caretTuneGrid

The caretTuneGrid is the RStudio addin for inserting tune parameters code for the caret package. 

[caretTuneGrid - github](https://github.com/milosvil/caretTuneGrid).

> esquisse

RStudio add-in to make plots with ggplot2 

[esquisse - github](https://github.com/dreamRs/esquisse)

> editData

RStudio addin for editing a ‘data.frame’ or a ‘tibble’

[Editing A ‘data.frame’](https://cran.r-project.org/web/packages/editData/vignettes/editData.html)

> Rcade

The goal of Rcade is to provide access to games in order to waste some times in RStudio. You can play 2048, Tetris, Mario, Pacman, Spider Solitaire and others.

> taskscheduleR

Schedule R scripts/processes with the Windows task scheduler. 

[taskscheduleR - vignettes ](https://cran.r-project.org/web/packages/taskscheduleR/README.html)

# R for FUN

> hexSticker

Create hexagon sticker in R





