---
output:
  html_document: 
    toc: true
    toc_float: true
---

# Connecting to database

* [Working on Data-Warehouse (SQL) with R](https://datascienceplus.com/working-on-data-warehouse-sql-with-r/) -- `dplyr`
* [Database Queries With R](https://rviews.rstudio.com/2017/10/18/database-queries-with-r/) -- `dplyr`
* [Getting started with PostgreSQL in R](https://datashenanigan.wordpress.com/2015/05/18/getting-started-with-postgresql-in-r/) -- `RPostgreSQL`
* [Connect to Database in R](http://rprogramming.net/connect-to-database-in-r/)
* [Setting up a database connection](https://github.com/suzanbaert/Resources_and_Bookmarks/blob/master/2_Useful_blogposts.md)
* [Introduction to MySQL with R](https://programminghistorian.org/en/lessons/getting-started-with-mysql-using-r)
* [SQL for LinkedIn](http://drenr.com/pages/html_files/linkedin_sql.html)
* [Handling large data sets with Google BigQuery and R](https://rpubs.com/shivanandiyer/BigRQuery)
* [Introduction to dplyr for Databases](https://rpubs.com/jladams/dbplyr)


# Data Wrangling

* [Data Manipulation with dpylyr](https://www.listendata.com/2016/08/dplyr-tutorial.html) -- `dplyr`
* [Manipulation de facteurs avec forcats](http://perso.ens-lyon.fr/lise.vaudor/manipulation-de-facteurs-avec-forcats/) -- `forcats`
* [dplyr tutorial](http://genomicsclass.github.io/book/pages/dplyr_tutorial.html) -- `dplyr`
* [dplyr In a Nutshell](https://github.com/trinker/dplyr_in_a_nutshell) -- `dplyr`
* [Introduction to apply](https://nsaunders.wordpress.com/2010/08/20/a-brief-introduction-to-apply-in-r/) 
* [Data Processing with dplyr & tidyr](https://rpubs.com/bradleyboehmke/data_wrangling) -- `dplyr`
* [How to explore and manipulate a dataset from the fivethirtyeight package in R](http://www.storybench.org/how-to-explore-a-dataset-from-the-fivethirtyeight-package-in-r/)
* [Repository for dplyr tutorials by Suzan Beart](https://github.com/suzanbaert/Dplyr_Tutorials) -- `dplyr`
* [Data Analysis exampple with ggplot and dplyr](https://www.sharpsightlabs.com/blog/data-analysis-example-r-supercars-part2/)
* [Joining Data in R with dplyr](https://rpubs.com/williamsurles/293454) -- `dplyr`
* [How do I make my own dplyr-style functions?](https://thisisnic.github.io/2018/04/16/how-do-i-make-my-own-dplyr-style-functions/) -- `dplyr`
* [Simplify Your Code with %>%](https://uc-r.github.io/pipe)


# Data Preparation

* [Feature Engineering using R](https://blogs.msdn.microsoft.com/microsoftrservertigerteam/2017/03/23/feature-engineering-using-r/)
* [Tutorial on 5 Powerful R Packages used for imputing missing values](https://www.analyticsvidhya.com/blog/2016/03/tutorial-powerful-packages-imputing-missing-values/)
* [Data Cleaning with R and the Tidyverse: Detecting Missing Values](https://www.dataoptimal.com/data-cleaning-with-r/)

# Explorative Data Analysis

* [Six Sigma DMAIC Series in R – Part 1](https://datascienceplus.com/six-sigma-dmaic-series-in-r-part-1/) -- `DMAIC`
* [Beautiful and Powerful Correlation Tables in R](https://neuropsychology.github.io/psycho.R/2018/05/20/correlation.html)
* [Explore Your Dataset in R](https://www.littlemissdata.com/blog/simple-eda)
* [D3 Charts for Non_D3 Users](https://www.kaggle.com/nulldata/d3-charts-for-r-users-with-sunburst)
* [A Brief Introduction to Various Correlation Coefficients and When to Use Which](https://blog.zenggyu.com/en/post/2019-06-11/a-brief-introduction-to-various-correlation-coefficients-and-when-to-use-which/)

# Visualization

* [A Compendium of Clean Graphs in R](http://shinyapps.org/apps/RGraphCompendium/index.php?licu=urn%3Ali%3Acontrol%3Ad_flagship3_feed-object&lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3B0F0dQBL5QtektJ0RziXCww%3D%3D)
* [R graphics](http://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html) -- `ggplot2`
* [high quality resources for doing data journalism with R](https://rddj.info/?utm_content=bufferc7064&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer#publication-quality-graphics) 
* [Top 50 ggplot2 Visualizations](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html) -- `ggplot2`
* [from Data to Viz](https://www.data-to-viz.com/#dendrogram)
* [Introduction to data visualization with R](https://talks.andrewheiss.com/utah-rug-dataviz/) -- `ggplot2` 
* [Visualising spatial data: from R to shiny - workshop](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/vspd-base-shiny.md)
* [Highlighting with ggplot2](https://www.littlemissdata.com/blog/highlight)
* [Happy collaboration with Rmd to docx](https://rmarkdown.rstudio.com/articles_docx.html)
* [Laying out multiple plots on a page](https://cran.r-project.org/web/packages/egg/vignettes/Ecosystem.html?utm_content=buffer44f79&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer) -- `ggplot2`
* [Chapter 1. Data Visualization with ggplot2](https://www.oreilly.com/library/view/r-for-data/9781491910382/ch01.html)  -- `ggplot2`
* [ggplot2](http://kbroman.org/Workshop_DataCarpNSBE/ggplot2.html)
* [Tutorial 5.2 - The Grammar of Graphics in R (ggplot2)](http://www.flutterbys.com.au/stats/tut/tut5.2.html)
* [ggplot2 extentions](http://www.ggplot2-exts.org/)
* [Plotly in R: How to make ggplot2 charts interactive with ggplotly](http://www.musgraveanalytics.com/blog/2018/8/24/how-to-make-ggplot2-charts-interactive-with-plotly) -- `ggplot2`, `plotly`
* [Comprehensive list of color palettes available in r](https://github.com/EmilHvitfeldt/r-color-palettes)
* [12 Extensions to ggplot2 for More Powerful R Visualizations](https://mode.com/blog/r-ggplot-extension-packages)
* [Mapping ggplot geoms and aesthetic parameters](https://www.yihanwu.ca/post/geoms-and-aesthetic-parameters/)
* [How to Turn Your ggplot2 Visualization into an Interactive Tweet](https://datatitian.com/how-to-turn-your-ggplot2-visualization-into-an-interactive-tweet/)
* [Themes and Labels](https://nilsreimer.com/post/gwtp-themes-labels/) -- `ggplot2`
* [A Detailed Guide to ggplot colors](https://michaeltoth.me/a-detailed-guide-to-ggplot-colors.html)
* [INTRODUCING 3D GGPLOTS WITH RAYSHADER](https://www.tylermw.com/3d-ggplots-with-rayshader/) -- `rayshader`

## Animation

* [Animating Your Data Visualizations Like a Boss Using R](https://towardsdatascience.com/animating-your-data-visualizations-like-a-boss-using-r-f94ae20843e3)
* [Factfulness](https://davidsmale.netlify.com/portfolio/factfulness/)
* [Using ggplot2 for functional time series](https://robjhyndman.com/hyndsight/ftsviz/)
* [gganimate: Animate YouR Security Analysis](https://holisticinfosec.io/post/gganimate-animate-your-security-analysis/)
* [Create Trending Animated Bar Charts using R](https://towardsdatascience.com/create-animated-bar-charts-using-r-31d09e5841da)

# Clustering 

* [A package for visualizing dendrograms](https://www.r-statistics.com/2015/08/dendextend-a-package-for-visualizing-adjusting-and-comparing-dendrograms-from-the-journal-bioinformatics/) --  `dendextend`
* [Difference Between K-Means And Hierarchical](https://stepupanalytics.com/difference-between-k-means-clustering-and-hierarchical-clustering/) -- `kmeans`
* [R Clustering](https://data-flair.training/blogs/r-clustering-tutorial/) -- `kmeans`
* [Hierarchical Cluster Analysis](https://afit-r.github.io/hc_clustering)
* [Hierarchical Clustering in R](https://www.datacamp.com/community/tutorials/hierarchical-clustering-R)
* [Where Kmeans clustering fails
Can DBSCAN be a solution?](https://datascience-enthusiast.com/Python/DBSCAN_Kmeans.html)
* [Determining The Optimal Number Of Clusters: 3 Must Know Methods](https://www.datanovia.com/en/lessons/determining-the-optimal-number-of-clusters-3-must-know-methods/)
* [Hierarchical Cluster Analysis](https://afit-r.github.io/hc_clustering)
* [K-means Clustering in R with Example](https://www.guru99.com/r-k-means-clustering.html)


# PCA

* [Principal Component Methods in R](http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/118-principal-component-analysis-in-r-prcomp-vs-princomp/#compute-pca-in-r-using-prcomp) -- `factoextra`
* [Principal Component Analysis in R](https://www.datacamp.com/community/tutorials/pca-analysis-r)
* [Principal component analysis : the basics you should read - R software and data mining](http://www.sthda.com/english/wiki/print.php?id=206#infos)
* [Introduzione al trattamento Statistico dei Dati](http://www.uniroma2.it/didattica/Sensori_ed_applic_2/deposito/lez5.pdf)
* [PRINCIPAL COMPONENT ANALYSIS (PCA)](http://rinterested.github.io/statistics/PCA.html)
* [Understanding PCA using stack overflow data](https://juliasilge.com/blog/stack-overflow-pca/)

# Machine Learning

* [modelDown: a website generator for your predictive models](http://smarterpoland.pl/index.php/2018/06/modeldown-a-website-generator-for-your-predictive-models/) -- `modelDown`
* [100 Days of ML Coding](Avik-Jain/100-Days-Of-ML-Code)
* [Bias-Variance Tradeoff in Machine Learning](https://www.learnopencv.com/bias-variance-tradeoff-in-machine-learning/)

## Regression

  * [Principal component regression in R](https://educationalresearchtechniques.com/2017/12/18/principal-component-regression-in-r/) -- `pls`
* [machine learning with CARET package in R ](https://www.analyticsvidhya.com/blog/2016/12/practical-guide-to-implement-machine-learning-with-caret-package-in-r-with-practice-problem/) --  `caret`
* [Going Deeper into Regression Analysis](https://www.analyticsvidhya.com/blog/2016/07/deeper-regression-analysis-assumptions-plots-solutions/)
* [Simple Guide to Logistic Regression in R](https://www.analyticsvidhya.com/blog/2015/11/beginners-guide-on-logistic-regression-in-r/)
* [7 Types of Regression Techniques you should know!](https://www.analyticsvidhya.com/blog/2015/08/comprehensive-guide-regression/)
* [Beginners Guide to Regression Analysis and Plot Interpretations](https://www.hackerearth.com/practice/machine-learning/machine-learning-algorithms/beginners-guide-regression-analysis-plot-interpretations/tutorial/)
* [Understanding Regression Error Metrics](https://www.dataquest.io/blog/understanding-regression-error-metrics/)
* [Residual Analysis in Linear Regression](https://rpubs.com/iabrady/residual-analysis)
* [Using Linear Regression to Predict Energy Output of a Power Plant](https://datascienceplus.com/linear-regression-predict-energy-output-power-plant/amp/)
* [Elegant regression results tables and plots in R: the finalfit package](http://www.datasurg.net/2018/05/16/elegant-regression-results-tables-and-plots-the-finalfit-package/)
* [Caret: an R package for machine learning](file:///C:/Users/aless/Downloads/Caret_Tutorial.html)

## Classification

* [Top 15 Evaluation Metrics for Classification Models](https://www.machinelearningplus.com/machine-learning/evaluation-metrics-classification-models-r/)
* [Tuning xgboost in R](https://insightr.wordpress.com/2018/05/17/tuning-xgboost-in-r-part-i/#more-809) -- `xgboost`
* [Predicting Binary Outcomes with R, gbm, glmnet ](https://amunategui.github.io/binary-outcome-modeling/) -- `caret`
* [Survival Prediction Models in R](https://datascienceplus.com/time-dependent-roc-for-survival-prediction-models-in-r/) -- `survival`
* [How to handle Imbalanced Classification ](https://www.analyticsvidhya.com/blog/2017/03/imbalanced-classification-problem/) 
* [Caret Package – A Practical](https://www.machinelearningplus.com/machine-learning/caret-package/) -- `caret`
* [Visualizing ML Models with LIME](http://uc-r.github.io/lime) -- `lime`|
* [Playing with dimensions](https://github.com/pablo14/post_cluster_tsne/blob/master/post.Rmd) -- `Rtsne` 
* [Top 10 Algorithms for Newbies](https://towardsdatascience.com/a-tour-of-the-top-10-algorithms-for-machine-learning-newbies-dde4edffae11)
* [Automated Feature Selection](https://www.statworx.com/de/blog/data-science/bouncer-0-1-2-automated-feature-selection/) -- `bounceR`
* [K NEAREST NEIGHBOR](https://www.listendata.com/2017/12/k-nearest-neighbor-step-by-step-tutorial.html) -- `caret``
* [Logistic Regression in R Tutorial](https://www.datacamp.com/community/tutorials/logistic-regression-R)
* [Code for Workshop: Introduction to Machine Learning with R](https://shirinsplayground.netlify.com/2018/06/intro_to_ml_workshop_heidelberg/)
* [Metric Functions in a Classification Dataset](http://rpubs.com/prcuny/161764) -- `caret`
* [caret machine learning repository](https://github.com/tobigithub/caret-machine-learning/wiki) -- `caret`
* [Unbox the Black Box: Part #1](https://www.kaggle.com/ankur310794/unbox-the-black-box-part-1) -- `lime`


## Tidymodels

* [A Gentle Introduction to tidymodels](https://rviews.rstudio.com/2019/06/19/a-gentle-intro-to-tidymodels/?utm_content=buffer25e57&utm_medium=social&utm_source=linkedin&utm_campaign=buffer)
* [Modelling with Tidymodels and Parsnip](https://medium.com/@diegousaiuk/modelling-with-tidymodels-and-parsnip-bae2c01c131c)
* [Modeling with `parsnip` and `tidymodels`](https://www.benjaminsorensen.me/post/modeling-with-parsnip-and-tidymodels/)
* [How to use recipes package from tidymodels for one hot encoding](https://blog-datascienceheroes-com.cdn.ampproject.org/c/s/blog.datascienceheroes.com/how-to-use-recipes-package-for-one-hot-encoding/amp/)
* [How to do feature engineering in R with the recipes package](https://ortom.co.uk/r/2019/07/12/How-to-do-feature-engineering-in-R-with-the-recipes-package.html)

## H2O

* [Plot H2O Decision Trees in R](https://www.h2o.ai/blog/finally-you-can-plot-h2o-decision-trees-in-r/)
* [H2O GBM Tuning Tutorial for R](https://blog.h2o.ai/2016/06/h2o-gbm-tuning-tutorial-for-r/)  
* [The one function call you need to know as a data scientist: h2o.automl](https://longhowlam.wordpress.com/2017/08/30/the-one-function-call-you-need-to-know-as-a-data-scientist-h2o-automl/) -- `h2o

# Outlier & Anomaly detection

* [A Python Toolkit for Scalable Outlier Detection (Anomaly Detection) ](https://github.com/yzhao062/pyod)
* [Techniques of Outlier Detection and Treatment](https://www.linkedin.com/pulse/techniques-outlier-detection-treatment-suhas-jk/)
* [Anomaly Detection Techniques: Defining Normal](https://www.darkreading.com/threat-intelligence/anomaly-detection-techniques-defining-normal-/a/d-id/1334116)
* [Using R and H2O to identify product anomalies during the manufacturing process.](https://laranikalranalytics.blogspot.com/2019/03/using-r-and-h2o-to-identify-product.html)

# Sparklyr

* [Predicting food preferences with sparklyr](https://shiring.github.io/machine_learning/2017/02/19/food_spark)
* [Machine learning and k-fold cross validation with sparklyr](https://eddjberry.netlify.com/post/2017-11-02-sparklyr/)
* [R and Spark: How to Analyze Data Using RStudio’s Sparklyr and H2O’s Rsparkling Packages](https://databricks.com/session/r-and-spark-how-to-analyze-data-using-rstudios-sparklyr-and-h2os-rsparkling-packages)
* [Manipulating Data with dplyr](https://beta.rstudioconnect.com/content/2025/dplyr.nb.html)
* [taxiDemoH2O.Rmd](https://github.com/rstudio/sparkDemos/blob/master/prod/presentations/sparkSummitEast/taxiDemoH2O.Rmd) 
* [Importing 30GB of data into R with sparklyr](http://www.brodrigues.co/blog/2018-02-16-importing_30gb_of_data/)
* [Comparison of ML Classifiers Using Sparklyr](https://beta.rstudioconnect.com/content/1518/notebook-classification.html)
* [Analyzing US flight map with sparklyr](https://rstudio-pubs-static.s3.amazonaws.com/244135_7fdd3eb63ef24e62be0e037e293ac95f.html)
* [Data Science Toolchain with Spark and R](http://colorado.rstudio.com:3939/content/420/taxiDemo.nb.html)
* [Data Science with Spark and R](https://github.com/edgararuiz/bigdatalondon2018)
* [Sparklyr Resources](https://beta.rstudioconnect.com/content/3046/Sparklyr_Resources.html)

# Deep Learning

* [Introducing Keras in R](http://rpubs.com/juanhklopper/introduction_to_keras)
* [Deep Learning in R](http://www.rblog.uni-freiburg.de/2017/02/07/deep-learning-in-r/)
* [Deep Learning with Keras and Shiny](http://jasdumas.com/2018-02-20-deep-learning-img-classifier/) -- `keras`
* [I_LOVE_IKEA_SHINY_APP](https://github.com/longhowlam/I_LOVE_IKEA_SHINY_APP) -- `keras`
* [R Markdown Notebooks for "Deep Learning with R"](https://github.com/jjallaire/deep-learning-with-r-notebooks) -- `keras`
* [Image classification with keras](https://shirinsplayground.netlify.com/2018/06/keras_fruits/) --`keras`
* [Explaining Keras image classification models with lime](https://shirinsplayground.netlify.com/2018/06/keras_fruits_lime/) -- `keras`
* [Kaggle #1 Winning Approach for Image Classification Challenge](https://medium.com/@shridhar743/kaggle-1-winning-approach-for-image-classification-challenge-9c1188157a86)
* [Advanced GaRdening with Convolutional NNs -- Kaggle kernel](https://www.kaggle.com/bonovandoo/advanced-gardening-with-convolutional-nns) -- `mxnet`
* [Deep Neural Networks](https://github.com/ledell/useR-machine-learning-tutorial/blob/master/deep-neural-networks.ipynb)
* [Deep Learning With Keras To Predict Customer Churn](http://blogs.rstudio.com/tensorflow/posts/2018-01-11-keras-customer-churn/) -- `keras`
* [How to create a sequential model in Keras for R](https://blog.datascienceheroes.com/how-to-create-a-sequential-model-in-keras-for-r/) -- `keras`
* [Code for case study - Customer Churn with Keras/TensorFlow and H2O](https://shirinsplayground.netlify.com/2018/12/customer_churn_code/)
* [Neural Network Models in R](https://www.datacamp.com/community/tutorials/neural-network-models-r)


## Image classification

* [Computer Vision with R & Keras](https://thecodeforest.github.io/post/computer_vision_with_r.html)
* [Applied Deep Learning - Part 4: Convolutional Neural Networks](https://towardsdatascience.com/applied-deep-learning-part-4-convolutional-neural-networks-584bc134c1e2)
* [Concepts in object detection](https://blogs.rstudio.com/tensorflow/posts/2018-12-18-object-detection-concepts/)
* [Example code Keras in R - VGG16 Base - Kaggle Kernel](https://www.kaggle.com/dkoops/keras-r-vgg16-base) -- `keras`
* [Image Classification with Keras](https://tensorflow.rstudio.com/blog/keras-image-classification-on-small-datasets.html) -- `keras`
* [Pre-trained model on R](https://tsmatz.wordpress.com/2017/05/25/image-classification-and-matching-with-r-microsoftml-featurizeimage/) -- `MicrosoftML`
* [Using Pre-Trained Models](https://tensorflow.rstudio.com/keras/articles/applications.html)
* [Predicting Irish electricity consumption with neural networks](http://www.michaeljgrogan.com/electricity-consumption-neural/amp/)
* [Satellite imagery generation with Generative Adversarial Networks ](https://appsilon.com/satellite-imagery-generation-with-gans/) -- `keras`
* [Transfer Learning with Keras in R](http://flovv.github.io/Logo_detection_transfer_learning/) -- `keras`
* [R vs Python: Image Classification with Keras](https://datascienceplus.com/r-vs-python-image-classification-with-keras/) -- `keras`
* [Image Classification with Keras in R & Python](https://adamspannbauer.github.io/2018/02/14/image-classification-r-and-python/)





# Time series analysis

* [Time Series of the World, Unite!](http://www.christophsax.com/2018/05/15/tsbox/) -- `tsbox`
* [Deep Learning for Time Series Forecasting](https://tensorflow.rstudio.com/blog/sunspots-lstm.html) -- `keras`
* [Introduction to Time Series Analysis](https://www.itl.nist.gov/div898/handbook/pmc/section4/pmc4.htm)
* [Forecasting time series using R](https://robjhyndman.com/talks/MelbourneRUG.pdf)
* [Using R for Time Series Analysis](http://a-little-book-of-r-for-time-series.readthedocs.io/en/latest/src/timeseries.html)
* [Exploring & Visualizing Time Series](https://uc-r.github.io/ts_exploration)
* [Plot Time Series Data Using GGPlot](http://www.sthda.com/english/articles/32-r-graphics-essentials/128-plot-time-series-data-using-ggplot/)
* [Preparing Datetime Data for Analysis with padr and dplyr](https://edwinth.github.io/blog/padr-examples/)
* [Moving Averages](http://uc-r.github.io/ts_moving_averages)
* [Introduction to Forecasting with ARIMA in R](https://www.datascience.com/blog/introduction-to-forecasting-with-arima-in-r-learn-data-science-tutorials)
* [Time Series Forecasting with Machine Learning: An example from Kaggle](https://redoakstrategic.com/time_series_forecasting_machine_learning/)
* [How to add Trend Lines in R Using Plotly](https://www.displayr.com/how-to-add-trend-lines-in-r-using-plotly/?utm_medium=Feed&utm_source=Syndication)
* [EDA+Prophet+ MLP Neural Network Forecasting](https://www.kaggle.com/arindamgot/eda-prophet-mlp-neural-network-forecasting) -- `prophet`
* [Generate Quick and Accurate Time Series Forecasts using Facebook’s Prophet](https://www.analyticsvidhya.com/blog/2018/05/generate-accurate-forecasts-facebook-prophet-python-r/) -- `prophet`
* [Time series animation](https://github.com/thomasp85/gganimate/wiki/Temperature-time-series?utm_campaign=Data_Elixir&utm_medium=email&utm_source=Data_Elixir_198)
* [Tidy forecasting in R](https://github.com/mitchelloharawild/fable-tfeam-2018)
* [Time Series Analysis for Business Forecasting with Artificial Neural Networks](https://www.business-science.io/business/2018/12/04/time-series-forecasting.html)
* Aautomate your kpi forecasts with only 1 line of r code using autots](https://www.remixinstitute.com/blog/automate-your-kpi-forecasts-with-only-1-line-of-r-code-using-autots/#.XO2SUogzY2w)

# Maps & Spatial Analysis

* [Drawing beautiful maps programmatically with R, sf and ggplot2](https://www.r-spatial.org//r/2018/10/25/ggplot2-sf.html)
* [Introduction to Mapping and Spatial Analysis with R](https://cengel.github.io/rspatial/)
* [Visualising italian wine production](https://www.mango-solutions.com/blog/Visualising-Italian-Wine-Production)

# Web Scraping

* [Practical Introduction to Web Scraping using R](https://www.r-bloggers.com/practical-introduction-to-web-scraping-in-r/amp/)
* [Web Scraping in R](http://applied-r.com/web-scrapping/)
* [Webscraping: (1) Server-side and CSS](https://raw.githack.com/uo-ec607/lectures/master/06-web-css/06-web-css.html)
* [Web Scraping in R](http://applied-r.com/web-scrapping/)


# Reporting

* [Getting Started with R Markdown](https://ourcodingclub.github.io/2016/11/24/rmarkdown-1.html) -- `rmarkdown`
* [Introduction to R Markdown](https://saghirb.github.io/shared/Rmarkdown-Intro-Workshop.html#1) -- `rmarkdown`
* [Build a Jekyll blog in minutes](https://github.com/barryclark/jekyll-now)
* [Job automation in R](https://www.worksmarter.pl/en/post/job-automation-r-1/) -- `rmarkdown`
* [bookdown cheatsheet](http://www.pzhao.org/en/post/bookdown-cheatsheet/) -- `bookdown`
* [A clean R Markdown template for your reports](https://github.com/holtzy/epuRate) -- `rmarkdown`
* [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) -- `rmarkdown`
* [Automatically knit R Markdown documents, build them with Jekyll, and serve the website with servr locally](https://github.com/yihui/blogdown-jekyll) -- `blogdown`
* [Deploying to Github pages with Travis](https://backendtea.github.io/deploy-travis-to-github)
* [Getting used to R, RStudio, and R Markdown](https://rbasics.netlify.com/index.html) -- `rmarkdown`
* [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
* [Up and running with blogdown](https://alison.rbind.io/post/up-and-running-with-blogdown/) -- `blogdown`
* [How to self-publish a book](https://blog.datascienceheroes.com/how-to-self-publish-a-book/)
* [Writing your thesis with bookdown](https://eddjberry.netlify.com/post/writing-your-thesis-with-bookdown/)
* [How to self-publish a book: Customizing Bookdown](https://blog.datascienceheroes.com/how-to-self-publish-a-book-customizing-bookdown/)
* [Pimp my RMD: a few tips for R Markdown](https://holtzy.github.io/Pimp-my-rmd/)
* [R Markdown](https://uc-r.github.io/r_markdown)
* [Getting Started with R Markdown](https://ourcodingclub.github.io/2016/11/24/rmarkdown-1.html)
* [Introduction to R Markdown](https://rpubs.com/brandonkopp/RMarkdown)
* [Render reports directly from R scripts](http://brooksandrew.github.io/simpleblog/articles/render-reports-directly-from-R-scripts/)
* [Pimp my RMD: a few tips for R Markdown](https://holtzy.github.io/Pimp-my-rmd/)
* [Comparing huxtable with other R packages for creating tables](https://hughjonesd.github.io/huxtable/design-principles.html)
* [Introducing vitae](https://blog.mitchelloharawild.com/blog/vitae/)
* [Style knitr Code Output Appearance in HTML with Custom CSS Classes](https://www.garrickadenbuie.com/blog/knitr-custom-class-output/)
* [How to build a website with Blogdown in R](http://www.storybench.org/how-to-build-a-website-with-blogdown-in-r/)
* [Using R Markdown for Class Reports](http://www.stat.cmu.edu/~cshalizi/rmarkdown/)
* [What is R Markdown?](https://scientistcafe.com/post/markdownreport#01_what_is_r_markdown)

# Shiny


* [RinteRface Shiny Server](http://www.rinterface.com/shiny.html)
* [An awesome R-shiny list!](https://grabear.github.io/awesome-rshiny/) -- `shiny`
* [A Shiny application in a package R](https://rtask.thinkr.fr/blog/our-shiny-template-to-design-a-prod-ready-app/) -- `shiny`
* [User authentication in R Shiny](https://appsilondatascience.com/blog/rstats/2018/05/30/user-authentication-in-r-shiny.html) -- `shiny`
* [Create dashboards with semantic.dashboard](https://appsilondatascience.com/blog/rstats/2018/06/11/dashboard-tutorial.html) -- `semantic.dashboard`
* [Shiny, R and HTML](https://www.sitepoint.com/shiny-r-and-html-merging-data-science-and-web-development/) -- `shiny`
* [Shiny Database App (CRUD)](https://ipub.com/shiny-crud-app/)
* [DOCKERIZED SHINY APP DEVELOPMENT](http://tamaszilagyi.com/blog/dockerized-shiny-app-development/?utm_content=buffer2d92f&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)
* [Creating Tools for Winning Teams](https://www.positiveresidual.com/) -- `shiny`
* [Building interface for you and your data](https://www.cultureofinsight.com/)
* [Build your first web app dashboard using Shiny and R <kbd>*</kbd>](https://medium.freecodecamp.org/build-your-first-web-app-dashboard-using-shiny-and-r-ec433c9f3f6c)
* [Shiny tips & tricks for improving your apps and solving common problems](https://github.com/daattali/advanced-shiny)
* [Adding Firebase Authentication to Shiny](https://www.tychobra.com/posts/2019-01-03-firebasse-auth-wtih-shiny/)
* [Deep Learning Image Classification with Keras and Shiny](https://jasminedaly.com/2018-02-20-deep-learning-img-classifier/)
* [Shiny application (with modules) - Saving and Restoring from RDS](https://www.radmuzom.com/2019/06/23/shiny-application-with-modules-saving-and-restoring-from-rds/)

# Shiny Code

* [Shiny Dashboard example](http://shiny.webpopix.org/dashboard/absorption/)
* [Building a Shiny web application to visualize spatial and spatio-temporal data](https://paula-moraga.github.io/tutorial-shiny-spatial/)
* [Basic Insurer Dashboard](https://github.com/Tychobra/shiny-insurance-examples/tree/master/basic-insurer-dashboard)
* [Example Shiny Apps](https://www.tychobra.com/shiny/)
* [Shinyapps Gallery](https://shinyapps-recent.appspot.com/recent.html)
* [shiny image classification  -- github](https://github.com/hussius/shiny-imageclassif-tfslim)

# Flexdashboard

* [Automated Dashboard with various correlation visualizations in R](https://www.r-bloggers.com/automated-dashboard-with-various-correlation-visualizations-in-r/amp/)

# Programming

* [Learning Functional Programming & purrr](https://paulvanderlaken.com/2018/12/05/learning-functional-programming-purrr/amp/)
* [R Markdown website for learning how to use purrr](https://jennybc.github.io/purrr-tutorial/index.html)
* [R Coding Style Guide](https://irudnyts.github.io/r-coding-style-guide/)
* [Building R Packages](http://girke.bioinformatics.ucr.edu/GEN242/mydoc_Programming_in_R_07.html)


# Making packages

* [Useful links by Suzan Baert: making packages](https://github.com/suzanbaert/Resources_and_Bookmarks/blob/master/2_Useful_blogposts.md)
* [A home for your functions: creating an R package](https://corinnovation.com/2019/04/26/creating-an-r-package/)
* [How to Create and Distribute an R Package](https://medium.com/@shiansu/how-to-create-and-distribute-an-r-package-a296217435dc)


# Deploy

* [Building a Package that Lasts](https://github.com/ColinFay/erum2018) -- `package`
* [A Scalable Predictive API with PFA](https://stevenmortimer.com/a-scalable-predictive-api-with-pfa-and-aws-lambda/) -- `aurelius`
* [Using R with Amazon](https://aws.amazon.com/it/blogs/machine-learning/using-r-with-amazon-sagemaker/) 
* [R can API and So Can You!](https://medium.com/@heathernolis/r-can-api-c184951a24a3)
* [Docker for R user](https://github.com/noamross/nyhackr-docker-talk)
* [Enterprise Web Services with Neural Networks Using R and TensorFlow](https://opensource.t-mobile.com/blog/posts/r-tensorflow-api/)
* [Beta release of SparkR job types in Cloud Dataproc](https://gweb-cloudblog-publish.appspot.com/products/ai-machine-learning/announcing-the-beta-release-of-sparkr-job-types-in-cloud-dataproc/amp/)
* [How to Deploy Externally Generated R Models to Azure Machine Learning Studio Web Services](https://medium.com/wandering-in-advanced-analytics/how-to-deploy-externally-generated-r-models-to-azure-machine-learning-studio-web-services-41a1a5ba9df)
* [An Introduction to Docker for R Users](https://colinfay.me/docker-r-reproducibility/)
* [Are you leaking h2o? Call plumber!](https://longhowlam.wordpress.com/2019/02/07/are-you-leaking-h2o-call-plumber/)

## Docker

* [RStudio in Docker – now share your R code effortlessly!](https://harini.blog/2019/05/25/rstudio-and-rshiny-in-docker/)


## AWS Tutorial

* [Using sparklyr with an Apache Spark cluster](https://spark.rstudio.com/examples/yarn-cluster-emr/)
* [Analytics at Scale: h2o, Apache Spark and R on AWS EMR](https://redoakstrategic.com/h2oaws/)
* [H2O & RStudio Server on Amazon Web Services (AWS), the Easy Way!](http://amunategui.github.io/h2o-on-aws/)
* [Scaling H2O analytics with AWS and p(f)urrr (Part 1)](https://www.daeconomist.com/post/2018-12011-aws-parti/)


# API & IDE

* [Google Analytics R Tutorial](http://www.ryanpraski.com/google-analytics-r-tutorial/) -- `googleAnalyticsR`
* [Big Data Platforms](http://www.rdatamining.com/big-data/big-data-platforms)
* [Powered By R](http://stagraph.com/Post?Id=31&Title=Powered+By+R#r_online)
* [Services and tools for building intelligent R applications in the cloud](http://blog.revolutionanalytics.com/2018/01/r-cloud-tools.html)
* [Working with APIs from R](https://stevenmortimer.com/presentations/working-with-apis-from-r/)
* [API Development with R Part-I](http://jaehyeon-kim.github.io/2017/11/API-Development-with-R-Part-I.html) -- `plumber` , `rApache`
*  [Iterative testing with plumber](https://irene.rbind.io/post/iterative-testing-plumber/)

# RSTUDIO TIPS

* [Code Snippets](https://support.rstudio.com/hc/en-us/articles/204463668-Code-Snippets?mobile_site=true)
* [4 ways to be more efficient using RStudio's Code Snippets](https://jozefhajnala.gitlab.io/r/r906-rstudio-snippets/)
* [Discover and install useful RStudio addins](https://github.com/daattali/addinslist)
* [RStudio IDE Easy Tricks You Might've Missed](https://rviews.rstudio.com/2016/11/11/easy-tricks-you-mightve-missed/)
* [Motivate yourself with an .Rprofile](https://www.rostrum.blog/2019/01/04/rprofile-motivate/)


# Teaching  

## DataScience

* [Machine Learning cheatsheets for Stanford's CS 229](https://github.com/afshinea/stanford-cs-229-machine-learning)
* [Data Science Cheatsheets](https://github.com/FavioVazquez/ds-cheatsheets)
* [Visual Introduction to probability and statistics](https://seeing-theory.brown.edu/index.html#firstPage)
* [Some datasets for teaching data science](https://simplystatistics.org/2018/01/22/the-dslabs-package-provides-datasets-for-teaching-data-science/)
* [Awesome Data Science repository](https://github.com/FavioVazquez/awesome-datascience)
* [Financial Times Visual Vocabulary](https://github.com/suzanbaert/Resources_and_Bookmarks/blob/master/2_Useful_blogposts.md)
* [The Data Visualisation Catalogue](https://datavizcatalogue.com/)
* [Teaching Data Science: A Short Course for Instructors](https://github.com/matrixds/teachingdatascience)
* [Carbon: Create and share beautiful images of your source code](https://carbon.now.sh/)
* [Everything you did and didn't know about PCA](http://alexhwilliams.info/itsneuronalblog/2016/03/27/pca/)
* [Data Science Interview Questions & Detailed Answers](https://rpubs.com/JDAHAN/172473)
* [6 Common Probability Distributions every data science professional should know](https://www.analyticsvidhya.com/blog/2017/09/6-probability-distributions-data-science/)
* [Visual Vocabulary](https://gramener.github.io/visual-vocabulary-vega/)
* [ML concepts explained Visually](http://setosa.io/ev/)
* [How to I interpret odds ratios in logistic regression](https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/)
* [Free SQL Download to practice queries](https://www.listendata.com/2019/06/free-sql-download-to-practice-queries.html?m=1)

----
* [End-to-End Machine Learning](https://brohrer.github.io/blog.html)
* [Student Classification Shiny App](https://teachdatascience.com/shiny2/)
* [ Introduction to Machine Learning for Coders!](http://course18.fast.ai/ml)

## R

* [Learn R Programming](https://www.tutorialspoint.com/r/index.htm)
* [Beyond Basic R - Introduction and Best Practices](https://owi.usgs.gov/blog/intro-best-practices/)
* [Getting used to R, RStudio, and R Markdown](https://rbasics.netlify.com/index.html)
* [Structuring R projects](https://chrisvoncsefalvay.com/structuring-r-projects/)
* [R for Data Science Solutions](https://jrnold.github.io/r4ds-exercise-solutions/)
* [Getting Started in R](https://github.com/eddelbuettel/gsir-te)
* [LeaRning Path on R](https://www.analyticsvidhya.com/learning-paths-data-science-business-analytics-business-intelligence-big-data/learning-path-r-data-science/)
* [RTutor: Interactive R Problem Sets](https://github.com/skranz/RTutor)
* [R PRACTICE EXERCISES: LEVEL 1](http://rstatistics.net/r-lang-practice-exercises-level-1-beginners/)
* [Programming Exercises for R](http://www.grappa.univ-lille3.fr/~mary/cours/stats/centrale/rexercises.pdf)
* [reproducible workflows workshop - github repository](https://github.com/bapalmer/reproducible-workflows) --`tidyverse` 
* [Data Science en production avec R](https://speakerdeck.com/colinfay/data-science-en-production-avec-r-quels-enjeux-quelles-solutions)
* [50 ways to show your data - r script](https://github.com/SQLThomas/Conferences/blob/master/SatRdayAms2018/50%20ways.R)
* [Rpubs collection by William Surles](https://rpubs.com/williamsurles)
* [A review of functions to get started simulating data in R](https://github.com/aosmith16/simulation-helper-functions)
* [Where do things live in R? R for Excel Users](http://rex-analytics.com/things-live-r-r-excel-users/?utm_content=bufferd74bd&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)
* [The Ultimate Opinionated Guide to Base R Date Format Functions](https://michaeltoth.me/the-ultimate-opinionated-guide-to-base-r-date-format-functions.html#the-ultimate-opinionated-guide-to-base-r-date-format-functions)
* [R Best practices](https://kdestasio.github.io/post/r_best_practices/)
* [Getting Started with Git and GitHub for R Users
](https://github.com/saghirb/Getting-Started-with-Git-and-GitHub-for-R-Users)
* [R: Best Resources to Learn R programming for Data Science](https://www-trainindata-com.cdn.ampproject.org/c/s/www.trainindata.com/amp/best-resources-to-learn-r-programming-for-data-science)

## Tidyverse

* [The tidyverse: dplyr, ggplot2, and friends](https://monashbioinformaticsplatform.github.io/r-more/topics/tidyverse.html)
* [Tidyverse for beginners](https://learningstatisticswithr.com/)
* [Animations of tidyverse verbs using R, the tidyverse, and gganimate](https://github.com/gadenbuie/tidy-animated-verbs/#tidy-data)
* [Introducing the Grammar of Graphics Plotting Concept](https://www.science-craft.com/2014/07/08/introducing-the-grammar-of-graphics-plotting-concept/)
* [teachthat - gather,spread, pipe](https://github.com/apreshill/teachthat)
* [Data Manipulation with dplyr](https://speakerdeck.com/omaymas/data-manipulation-with-dplyr-first-steps)
* [Intro to the Tidyverse Workshops](https://github.com/OmaymaS/datafest_tidyverse_workshop)
* [tidyverse - Davis R-Users’ Group](https://github.com/michaellevy/tidyverse_talk)
* [How to Filter in R: A Detailed Introduction to the dplyr Filter Function](https://michaeltoth.me/how-to-filter-in-r-a-detailed-introduction-to-the-dplyr-filter-function.html)
* [R-Ladies Sydney!](https://rladiessydney.org/)
* [A Beginner’s Guide to Tidyverse – The Most Powerful Collection of R Packages for Data Science](https://www.analyticsvidhya.com/blog/2019/05/beginner-guide-tidyverse-most-powerful-collection-r-packages-data-science/)
* [Data Wrangling in R](https://rstudio-pubs-static.s3.amazonaws.com/109948_876c577ae6424d47b529fce960db7bf4.html#1)
* [A Gentle Introduction to Tidy Statistics in R](https://resources.rstudio.com/webinars/a-gentle-introduction-to-tidy-statistics-in-r?utm_content=buffer61849&utm_medium=social&utm_source=twitter&utm_campaign=buffer)
* [Bang Bang – How to program with dplyr](https://www.statworx.com/de/blog/bang-bang-how-to-program-with-dplyr/)


## Teaching Shiny

* [Shiny Tutorials](https://github.com/debruine/shiny-tutorials)
* [Learn R Shiny through studying the rise in ocean plastics - Part One](https://www.linkedin.com/pulse/learn-r-shiny-through-studying-rise-ocean-plastics-part-mcnulty/)
* [Using Shiny in the Classroom](https://teachdatascience.com/shiny2/)
* [Materials for the Intro to Shiny workshop with RLadies Nijmegen ](https://github.com/sowla/2019-shiny-intro-workshop-Nijmegen-RLadies)


# RPubs must read

## Basic

* [Learning R on iris](https://rpubs.com/moeransm/intro-iris)
* [Missing Value Treatment](http://rstudio-pubs-static.s3.amazonaws.com/233370_56612580566d4c46a10ff2f70fa858a4.html)
* [Cluster Analysis with R](https://rstudio-pubs-static.s3.amazonaws.com/33876_1d7794d9a86647ca90c4f182df93f0e8.html)
* [Classification with Decision Trees](http://rpubs.com/kjmazidi/195428)
* [kNN Using caret R package](https://rpubs.com/njvijay/16444)
* [Pie Chart Revisited](http://rpubs.com/cardiomoon/398623)
* [Naive Bayes Classifier: theory and R example](https://rpubs.com/riazakhan94/naive_bayes_classifier_e1071)

## Advanced

* [Classifications in R](http://www.rpubs.com/arifulmondal/scoring)
* [Market basket analysis](https://rpubs.com/sbushmanov/180410)
* [Fraud Detection with Machine Learning](https://rpubs.com/kieroneil/321413)
* [Machine Learning, Key to Your Formulation Challenges](https://rpubs.com/m3cinc/machine_learning_key_to_your_formulation_challenges)
* [Data Analysis in Semiconductor Manufacturing ](https://rpubs.com/jeff_datascience/Semiconductor_Manufacturing)

# Kaggle kernel

* [Happiness 2017 (Visualization + Prediction)
](https://www.kaggle.com/javadzabihi/happiness-2017-visualization-prediction/notebook?utm_medium=social&utm_source=facebook.com&utm_campaign=Weekly-Kernel-Awards)
* [Stack Overflow 2018 survey: age, gender, sexuality](https://www.kaggle.com/heesoo37/stack-overflow-2018-survey-age-gender-sexuality?utm_medium=social&utm_source=linkedin.com&utm_campaign=Weekly-Kernel-Awards)
* [Breast Cancer or Not (with 15 ML)](https://www.kaggle.com/mirichoi0218/classification-breast-cancer-or-not-with-15-ml)
* [Exploring Survival on the Titanic](https://www.kaggle.com/mrisdal/exploring-survival-on-the-titanic) 
* [Detailed Data Analysis & Ensemble Modeling](https://www.kaggle.com/tannercarbonati/detailed-data-analysis-ensemble-modeling) -- `caret`
* [Exploratory Analysis -  Instacart](https://www.kaggle.com/philippsp/exploratory-analysis-instacart) -- `ggplot2`
* [R/rmd kaggle Kernels ordered by votes](https://www.kaggle.com/kernels?group=everyone&language=R&pageSize=20&sortBy=votes)
* [Resources for R](http://edrub.in/ARE212/resources.html)
* [Woggler- The Women Kaggler](https://www.kaggle.com/farazrahman/woggler-the-women-kaggler)

# Case studies

* [Which promotion should be used to increase sales? A fast-food chain’s marketing campaign case study](https://towardsdatascience.com/which-promotion-should-be-used-to-increase-sales-c1c91b4ffb34)
* [How to model with gradient boosting machine in R](http://www.storybench.org/tidytuesday-bike-rentals-part-2-modeling-with-gradient-boosting-machine/)

# Conference

## 2019

* [rstudio-conf 2019 Workshop materials](https://github.com/rstudio/rstudio-conf/blob/master/2019/workshops.md)
* [Speaker slides and materials for SatRday Chicago 2019](https://github.com/satRdays/newcastle2019-slides)
* [NEW YORK R CONFERENCE](https://www.rstats.nyc/2019/nyr/)
* [useR2019](https://github.com/sowla/useR2019-materials)
* [Keynote lectures at useR! 2019](https://www.youtube.com/channel/UC_R5smHVXRYGhZYDJsnXTwg/videos?view=57&flow=grid)

# Github repository

* [Data Analysis with R](https://github.com/susanli2016/Data-Analysis-with-R)
* [Presentations from H2O meetups & conferences by the H2O.ai team](https://github.com/h2oai/h2o-meetups)
* [H2O for Internet of Things + Deep Water project](https://github.com/h2oai/h2o-meetups/tree/master/2016_10_10_Data_Science_Milan)
* [hex-stickers](https://github.com/mkearney/hex-stickers)
* [BuzzFeedNews/everything](https://github.com/BuzzFeedNews/everything#standalone-datasets)
* [Links to slides from rstudio::conf 2019](https://github.com/kbroman/RStudioConf2019Slides)

# R Programming

* [Writing an R package from scratch](https://r-mageddon.netlify.com/post/writing-an-r-package-from-scratch/)
* [R Code – Best practices](http://www.thertrader.com/2018/09/01/r-code-best-practices/)
* [usethis workflow for package development](https://www.hvitfeldt.me/2018/09/usethis-workflow-for-package-development/)
* [Code Smells and Feels](https://github.com/jennybc/code-smells-and-feels#readme)
* [Machine Learning Cheatsheet Data set](https://ml-cheatsheet.readthedocs.io/en/latest/datasets.html)
* [R package primer](https://kbroman.org/pkg_primer/)


# Datasets

* [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets)
* [8 Fun Machine Learning Projects for Beginners](https://elitedatascience.com/machine-learning-projects-for-beginners?utm_content=buffere966c&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer&lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BlUa9rTKnSle%2FhXzYuGdA6Q%3D%3D)
* [Datasets to Practice Your Data Mining](Datasets to Practice Your Data Mining)
* [Generate random data sets](https://github.com/trinker/wakefield)
* [Data Science Projects](https://www.analyticsvidhya.com/blog/2018/05/24-ultimate-data-science-projects-to-boost-your-knowledge-and-skills/)
* [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets)
* [16 Strange Datasets for Machine Learning](https://gengo.ai/articles/16-strange-datasets-for-machine-learning/)
* [UKgrid](https://github.com/RamiKrispin/UKgrid)
* [Data & Code at FiveThirtyEightabc news](https://data.fivethirtyeight.com/)
* [Cool Datasets](https://www.cooldatasets.com/)
* [Google dataset search](https://toolbox.google.com/datasetsearch)
* [Global spending on R&D](http://uis.unesco.org/apps/visualisations/research-and-development-spending/)
* [Retrieve oil price data from eia.gov](https://github.com/eafpres/oil_prices)
* [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets)
* [Formatted datasets for Machine Learning With R by Brett Lantz](https://github.com/stedy/Machine-Learning-with-R-datasets)
* [Applied Predictive Modeling](http://appliedpredictivemodeling.com/data/)
* [R dataset](https://vincentarelbundock.github.io/Rdatasets/datasets.html)
* [Official repo for the #tidytuesday project](https://github.com/rfordatascience/tidytuesday)
* [Outlier Detection DataSets (ODDS)](http://odds.cs.stonybrook.edu/)
* [UCI Machine Learning Repository in R](https://ucimlr.netlify.com/)
* [SMS Spam Collection](http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/)



## Datasets for smart factory

* [Combined Cycle Power Plant Data Set](https://archive.ics.uci.edu/ml/datasets/Combined+Cycle+Power+Plant)